### ISSUE TITLE
Maken deelmodel IMBOR-SW - Acties

### ISSUE THREAD

**Issue by MarinusVonhof** [StichtingRIONED/imbor-sw#2]
De klasse DeelmodelImbor toegevoegd aan het GWSW datamodel (gwsw:DeelmodelImbor).
Is een conformiteitsklasse (nr 6) op de CoF's TOP, BAS, MDS en HYD.

Hoe bepalen wat exclusief GWSW binnen IMBOR op basis van de Access-tabellen (zie ook repos gwsw_worker).
Klasse/attribuut hoort bij IMBOR-SW als:
- De klasse inclusief alle attributen alleen voorkomt bij informatiemodel GWSW in de tabel KlassenAttributen
- De klasse/attribuut ontbreekt in de tabel KlassenAttributen (bijvoorbeeld supertypes) maar heeft wel alleen de Zoekingang "Stedelijk Water"

20241122/mv **Vragen en opmerkingen**:
- Wat is ons eindproduct, hoe wordt IMBOR 2025 gepubliceerd? Wat gebruikt de softwareleverancier?
- Klassen+Attributen die bij GWSW horen kunnen vervallen in IMBOR-Kern? Zie de lijst [Niet in IMBOR kern.txt](https://github.com/StichtingRIONED/imbor-sw/blob/main/Niet%20in%20IMBOR%20kern.txt).
- Hoe omgaan met GWSW-attributen die aanvullend zijn op supertypes uit IMBOR-Kern, gewoon toevoegen? Zie testomgeving: [Rioolleiding](https://data.gwsw.nl/1.6.1/IMBOR-SW/index.html?menu_item=classes&item=../../def/1.6.1/IMBOR-SW/Rioolleiding).
- Hoe omgaan met geërfde IMBOR-attributen die niet in datasets (OroX) gebruikt worden? Laten staan met markering? Zie testomgeving: [Rioolleiding](https://data.gwsw.nl/1.6.1/IMBOR-SW/index.html?menu_item=classes&item=../../def/1.6.1/IMBOR-SW/Rioolleiding).
- Hoe omgaan met specifieke GWSW-attributen binnen een IMBOR-concept? IMBOR houden, niet vanuit GWSW? Zie testomgeving, **wandruwheid** bij: [Rioolleiding](https://data.gwsw.nl/1.6.1/IMBOR-SW/index.html?menu_item=classes&item=../../def/1.6.1/IMBOR-SW/Rioolleiding)
- Zijn subproperties toegestaan? Werkt wel RDF-conform, als een Rioolleiding een gwsw:diameterLeiding heeft dan heeft de Rioolleiding ook een imbor:diameter. Zie testomgeving: [diameterLeiding](https://data.gwsw.nl/1.6.1/IMBOR-SW/index.html?menu_item=classes&item=../../def/1.6.1/IMBOR-SW/DiameterLeiding)
- Idem voor IMBOR-concepten die voorlopig in OroX een gwsw-naam hebben. In rdfs:comment de alternatieve naam opnemen?
- Multiparent in IMBOR geeft dubbele properties, die opschonen? (geërfde props uniek houden of parent eruit) Zie testomgeving: [Rioolleiding](https://data.gwsw.nl/1.6.1/IMBOR-SW/index.html?menu_item=classes&item=../../def/1.6.1/IMBOR-SW/Rioolleiding).
- In de Excel-mapping minimale alle top-concepten uitwerken, kolom Name IMBOR-SW moet gevuld zijn (controleren)
- In de Excel-mapping de gele cellen in de kolom Remarks bespreken

**Comment by RiX012** [comment]
> * Wat is ons eindproduct, hoe wordt IMBOR 2025 gepubliceerd? Wat gebruikt de softwareleverancier?

IMBOR2025 wordt als AccessDatabase opgeleverd, als NEN2660-2 ontologie in RDF, MIM-LD ontologie in RDF en SKOS vocabulaire. De softwareleveranciers gebruiken de tabellen uit Access of de RDF distributie. 

> Klassen+Attributen die bij GWSW horen kunnen vervallen in IMBOR-Kern? Zie de lijst [Niet in IMBOR kern.txt](https://github.com/StichtingRIONED/imbor-sw/blob/main/Niet%20in%20IMBOR%20kern.txt).

Het idee is dat IMBOR-SW bij ons aangeleverd wordt en dat we deze importeren in de Accesdatase. Dit 'vervangt' de IMBOR URI (identifier) door GWSW URI. De procedure zou moeten zijn dat wij bij een update van GWSW weer een nieuwe versie in IMBOR Access kunnen importeren. 

> Hoe omgaan met GWSW-attributen die aanvullend zijn op supertypes uit IMBOR-Kern, gewoon toevoegen? Zie testomgeving: [Rioolleiding](https://data.gwsw.nl/1.6.1/IMBOR-SW/index.html?menu_item=classes&item=../../def/1.6.1/IMBOR-SW/Rioolleiding).

Ja, die kunnen gewoon geintroducueerd worden.

>Hoe omgaan met geërfde IMBOR-attributen die niet in datasets (OroX) gebruikt worden? Laten staan met markering? Zie testomgeving: [Rioolleiding](https://data.gwsw.nl/1.6.1/IMBOR-SW/index.html?menu_item=classes&item=../../def/1.6.1/IMBOR-SW/Rioolleiding).

Ja dat zou ik prima vinden.

> Hoe omgaan met specifieke GWSW-attributen binnen een IMBOR-concept? IMBOR houden, niet vanuit GWSW? Zie testomgeving, wandruwheid bij: [Rioolleiding](https://data.gwsw.nl/1.6.1/IMBOR-SW/index.html?menu_item=classes&item=../../def/1.6.1/IMBOR-SW/Rioolleiding)

Ok. Wandruwheid is dus een GWSW attribuut die gebruikt wordt op een IMBOR type (Holle leiding). Als dit voorkomt gaat het attribuut naar IMBOR toe. 

> * Zijn subproperties toegestaan? Werkt wel RDF-conform, als een Rioolleiding een gwsw:diameterLeiding heeft dan heeft de Rioolleiding ook een imbor:diameter. Zie testomgeving: [diameterLeiding](https://data.gwsw.nl/1.6.1/IMBOR-SW/index.html?menu_item=classes&item=../../def/1.6.1/IMBOR-SW/DiameterLeiding)

Die zijn toegestaan. We gaan er vanuit dat GWSW aanvullende properties levert. Dus diameter en diameterLeiding kunnen dan allebei voorkomen. Deze moeten dan wel subproperties van elkaar zijn. Hierdoor kunnen leveranciers dan de waarde daadwerkelijk afleiden. 
Bij IMBOR in Access moeten we dan nog wel kijken hoe we met abstract en contreet omgaan op properties. Oplossing zou zijn om dit te laten varen/versoepelen voor properties.

> Idem voor IMBOR-concepten die voorlopig in OroX een gwsw-naam hebben. In rdfs:comment de alternatieve naam opnemen?

Dit gaat over IMBOR attributen die ook een GWSW URI moeten houden (voor Orox). Voorlopig nemen we dan de GWSW URI over in de toelichting van IMBOR attribuut

> Multiparent in IMBOR geeft dubbele properties, die opschonen? (geërfde props uniek houden of parent eruit) Zie testomgeving: [Rioolleiding](https://data.gwsw.nl/1.6.1/IMBOR-SW/index.html?menu_item=classes&item=../../def/1.6.1/IMBOR-SW/Rioolleiding).

De geërfde properties moeten uniek blijven. Dit zijn toch dezelfde triples. 
Waarschijnlijk als we dit importeren in de AccessDatabase komt dit goed. Maar dit moet gecheckt worden hoe de RDF er uit komt.

**Comment by RiX012** [comment]
> Klassen+Attributen die bij GWSW horen kunnen vervallen in IMBOR-Kern? Zie de lijst [Niet in IMBOR kern.txt](https://github.com/StichtingRIONED/imbor-sw/blob/main/Niet%20in%20IMBOR%20kern.txt).

Wanneer we de IMBOR URI (identifier) vervangen door GWSW URI zou dit goed zijn toch?

> > * Wat is ons eindproduct, hoe wordt IMBOR 2025 gepubliceerd? Wat gebruikt de softwareleverancier?
> 
> IMBOR2025 wordt als AccessDatabase opgeleverd, als NEN2660-2 ontologie in RDF, MIM-LD ontologie in RDF en SKOS vocabulaire. De softwareleveranciers gebruiken de tabellen uit Access of de RDF distributie.
> 
> > * Zijn subproperties toegestaan? Werkt wel RDF-conform, als een Rioolleiding een gwsw:diameterLeiding heeft dan heeft de Rioolleiding ook een imbor:diameter. Zie testomgeving: [diameterLeiding](https://data.gwsw.nl/1.6.1/IMBOR-SW/index.html?menu_item=classes&item=../../def/1.6.1/IMBOR-SW/DiameterLeiding)
> 
> Die zijn toegestaan. Het is dan wel zaak om aan te geven welke abstract of concreet zijn.
> 
> > Multiparent in IMBOR geeft dubbele properties, die opschonen? (geërfde props uniek houden of parent eruit) Zie testomgeving: [Rioolleiding](https://data.gwsw.nl/1.6.1/IMBOR-SW/index.html?menu_item=classes&item=../../def/1.6.1/IMBOR-SW/Rioolleiding).
> 
> De geërfde properties moeten uniek blijven. Dit zijn toch dezelfde triples?

**Comment by MarinusVonhof** [comment]
> * Zijn subproperties toegestaan? Werkt wel RDF-conform, als een Rioolleiding een gwsw:diameterLeiding heeft dan heeft de Rioolleiding ook een imbor:diameter. Zie testomgeving: [diameterLeiding](https://data.gwsw.nl/1.6.1/IMBOR-SW/index.html?menu_item=classes&item=../../def/1.6.1/IMBOR-SW/DiameterLeiding)

> Die zijn toegestaan. We gaan er vanuit dat GWSW aanvullende properties levert. Dus diameter en diameterLeiding kunnen dan allebei voorkomen. Deze moeten dan wel subproperties van elkaar zijn. Hierdoor kunnen leveranciers dan de waarde daadwerkelijk afleiden. 
Bij IMBOR in Access moeten we dan nog wel kijken hoe we met abstract en contreet omgaan op properties. Oplossing zou zijn om dit te laten varen/versoepelen voor properties.

Dit kunnen we ook oplossen met de IMBOR-prop "diameter" als property in IMBOR-SW. Er is toch een comment nodig om toe te lichten hoe het in OroX opgenomen wordt, daarin kan dan verwezen worden naar gwsw:hasAspect gwsw:DiameterLeiding.

**Comment by MarinusVonhof** [comment]
Nog bespreken: 
* In de mapping-spreadsheet [(bestand Mapping GWSW IMBOR.xlsm)](https://github.com/StichtingRIONED/imbor-sw/blob/main/Mapping%20GWSW%20IMBOR.xlsm) is in blad "IMBOR-Kern concepten" een extra controle op de verdeling SW/Kern gedaan. 
* De geel gemarkeerde concepten svp bespreken, blijft het IMBOR-Kern of wordt het IMBOR-SW?
* Het concept nen2660:EnumerationType is niet gedefinieerd in IMBOR-Kern (de andere nen2660-dingen wel)
* Andere onderscheidende kenmerken (gwsw:Uitvoering) meeleveren via de prop gwsw:uitvoering ?

**Comment by MarinusVonhof** [comment]
Het vorige comment is besproken op 13 dec 2024 (Rik, Jochem, Marinus)
* De items op spreadsheet-blad "IMBOR-Kern concepten" zijn doorgenomen en verdeeld over Top en SW
* In de NEN2660 zijn geen relaties opgenomen die als onderscheidend kenmerk kunnen worden gebruikt (analoog aan gwsw:functie/nen2660:executes)
